export type CategorySlug =
  | "nightlife"
  | "restaurant"
  | "cafe"
  | "beach"
  | "outdoor"
  | "event"
  | "travel"
  | "retail"
  | "cowork"

export type JourneyDuration = "short" | "half-day" | "full-day" | "evening" | "late"
export type TimeOfDay = "morning" | "afternoon" | "evening" | "late"

export interface TrendingCategory {
  slug: CategorySlug
  title: string
  summary: string
  highlight: string
  timeOfDay: TimeOfDay
  accent: string
}

export interface JourneyStop {
  time: string
  title: string
  description: string
  category: CategorySlug
  tags: string[]
}

export interface SmartJourney {
  id: string
  title: string
  summary: string
  vibe: string
  duration: JourneyDuration
  timeOfDay: TimeOfDay
  categories: CategorySlug[]
  stops: JourneyStop[]
}

export interface DiscoverCrew {
  id: string
  name: string
  category: CategorySlug
  start: string
  location: string
  capacity: { filled: number; total: number }
  description: string
  compatibility: number
  tags: string[]
  icon: string
}

export interface FriendsTemplate {
  id: string
  label: string
  categories: CategorySlug[]
  summary: string
  duration: JourneyDuration
  tags: string[]
}

export interface ModeSpotlight {
  mode: "Solo" | "Discover" | "Friends"
  headline: string
  description: string
  stats: { label: string; value: string; caption: string }[]
  playbook: string[]
  cta: { label: string; href: string }
}

export interface CitySignal {
  id: string
  category: CategorySlug
  status: "Trending" | "Peaking" | "Watch"
  change: number
  metric: string
  descriptor: string
}

export interface CityEventHighlight {
  id: string
  title: string
  time: string
  category: CategorySlug
  location: string
  callout: string
}

export interface VisualShowcase {
  id: string
  title: string
  subtitle: string
  category: CategorySlug
  image: string
  location: string
  tags: string[]
  description: string
  cta: { label: string; href: string }
}

export interface ExplorePlace {
  id: string
  name: string
  category: CategorySlug
  description: string
  neighborhood: string
  distanceKm: number
  budget: "<$30" | "$30-$60" | "$60-$100" | "$100+"
  timeOfDay: TimeOfDay
  duration: JourneyDuration
  tags: string[]
  openNow: boolean
  slot?: string
  image: string
  rating: number
  reviews: number
  isCrewFriendly: boolean
}

export const trendingByCategory: TrendingCategory[] = [
  {
    slug: "nightlife",
    title: "Nightlife",
    summary: "Gallery opening + rooftop set",
    highlight: "Queue-less entry and curated afters",
    timeOfDay: "evening",
    accent: "bg-emerald-500/20 text-emerald-200",
  },
  {
    slug: "restaurant",
    title: "Restaurants",
    summary: "Chef tables & hidden tastings",
    highlight: "Realtime table swap if plans shift",
    timeOfDay: "evening",
    accent: "bg-amber-500/15 text-amber-200",
  },
  {
    slug: "cafe",
    title: "Cafés",
    summary: "Third-wave espresso crawl",
    highlight: "Power outlets + study mood tracker",
    timeOfDay: "morning",
    accent: "bg-sky-500/15 text-sky-200",
  },
  {
    slug: "beach",
    title: "Beaches",
    summary: "Sunrise swim + coastline brunch",
    highlight: "Tide charts + sunrise alarms",
    timeOfDay: "morning",
    accent: "bg-cyan-500/15 text-cyan-100",
  },
  {
    slug: "outdoor",
    title: "Outdoors",
    summary: "Trail run + picnic overlook",
    highlight: "Weather + transit synced in",
    timeOfDay: "morning",
    accent: "bg-lime-500/15 text-lime-100",
  },
  {
    slug: "event",
    title: "Events",
    summary: "Indie market + rooftop jazz",
    highlight: "Ticket drops and queue status",
    timeOfDay: "afternoon",
    accent: "bg-purple-500/15 text-purple-200",
  },
  {
    slug: "travel",
    title: "Travel",
    summary: "Weekender escape itinerary",
    highlight: "Transport + stay curated in-app",
    timeOfDay: "morning",
    accent: "bg-rose-500/15 text-rose-200",
  },
  {
    slug: "retail",
    title: "Shops & Retail",
    summary: "Vintage crawl + ramen finisher",
    highlight: "Inventory intel + queue times",
    timeOfDay: "afternoon",
    accent: "bg-fuchsia-500/15 text-fuchsia-200",
  },
]

export const smartJourneys: SmartJourney[] = [
  {
    id: "sunrise-coastline",
    title: "Sunrise beach + coffee ritual",
    summary: "Saltwater start, slow roast finish, city still asleep.",
    vibe: "Calm \u2192 Energised",
    duration: "half-day",
    timeOfDay: "morning",
    categories: ["beach", "cafe", "outdoor"],
    stops: [
      {
        time: "06:15",
        title: "Sunrise dip at North Point",
        description: "Heated towels waiting, playlist to match the first light.",
        category: "beach",
        tags: ["sunrise", "swim", "calm seas"],
      },
      {
        time: "07:30",
        title: "Pour-over at Lumen Lab",
        description: "Reserved window bench, pastries pre-ordered.",
        category: "cafe",
        tags: ["third-wave", "pastry pre-order"],
      },
      {
        time: "09:00",
        title: "Clifftop walk",
        description: "Waypoint alerts you when the path gets crowded.",
        category: "outdoor",
        tags: ["scenic", "crowd-aware"],
      },
    ],
  },
  {
    id: "thrift-ramen",
    title: "Thrift crawl + ramen night",
    summary: "Indie finds, clean tailoring, broth that hits.",
    vibe: "Social \u2192 Cozy",
    duration: "full-day",
    timeOfDay: "afternoon",
    categories: ["retail", "event", "restaurant"],
    stops: [
      {
        time: "13:00",
        title: "Vintage block takeover",
        description: "Vendors filtered for your sizes + styles.",
        category: "retail",
        tags: ["vintage", "indie"],
      },
      {
        time: "16:30",
        title: "Upcycled workshop",
        description: "Hands-on slot with local designer, tools provided.",
        category: "event",
        tags: ["workshop", "design"],
      },
      {
        time: "19:00",
        title: "Broth Society",
        description: "Chef counter seats, dietary notes pre-loaded.",
        category: "restaurant",
        tags: ["ramen", "chef's table"],
      },
    ],
  },
  {
    id: "gallery-jazz",
    title: "Gallery stroll + late jazz",
    summary: "Immersive art, hidden lounge, last train lined up.",
    vibe: "Culture \u2192 After dark",
    duration: "half-day",
    timeOfDay: "evening",
    categories: ["event", "nightlife", "cafe"],
    stops: [
      {
        time: "17:45",
        title: "Curated gallery hop",
        description: "Waypoint arranges private preview slots.",
        category: "event",
        tags: ["art", "private access"],
      },
      {
        time: "19:30",
        title: "Aperitif bar",
        description: "Menu filtered to your flavour profile.",
        category: "cafe",
        tags: ["aperitif", "low-abv"],
      },
      {
        time: "21:15",
        title: "Basement jazz lounge",
        description: "Seamless door entry, setlist aligned to your vibe.",
        category: "nightlife",
        tags: ["live", "reserved seating"],
      },
    ],
  },
  {
    id: "coastal-hike",
    title: "Coastal hike + brunch",
    summary: "Golden trails, cooldown brunch, playlists set.",
    vibe: "Active \u2192 Refuel",
    duration: "half-day",
    timeOfDay: "morning",
    categories: ["outdoor", "cafe", "restaurant"],
    stops: [
      {
        time: "08:00",
        title: "Trail meet",
        description: "Gear checklist + weather briefing inside the app.",
        category: "outdoor",
        tags: ["hike", "sunrise"],
      },
      {
        time: "10:30",
        title: "Viewpoint stretch",
        description: "Waypoint drops a time-lapse prompt for the crew.",
        category: "outdoor",
        tags: ["photos", "group"],
      },
      {
        time: "11:30",
        title: "Post-hike brunch",
        description: "Pre-ordered recovery spread with dietary sync.",
        category: "restaurant",
        tags: ["brunch", "recovery"],
      },
    ],
  },
]

export const discoverCrews: DiscoverCrew[] = [
  {
    id: "crew-sunrise-hike",
    name: "Sunrise ridge run",
    category: "outdoor",
    start: "Sat • 05:45",
    location: "Skyline trail",
    capacity: { filled: 5, total: 8 },
    description: "Trail runners + sunrise chasers, coffee truck waiting at the summit.",
    compatibility: 93,
    tags: ["pace: steady", "sunrise", "gear check"],
    icon: "mountain",
  },
  {
    id: "crew-cafe-hunt",
    name: "Hidden café crawl",
    category: "cafe",
    start: "Sun • 10:00",
    location: "East Borough",
    capacity: { filled: 6, total: 8 },
    description: "Slow mornings, single origin tastings, sketchbook crowd welcome.",
    compatibility: 88,
    tags: ["creative", "mellow", "notebook"],
    icon: "coffee",
  },
  {
    id: "crew-market",
    name: "Indie market night",
    category: "event",
    start: "Fri • 18:30",
    location: "Riverside arcade",
    capacity: { filled: 9, total: 12 },
    description: "Local makers, live sets, market bites, all ticketed via Waypoint.",
    compatibility: 91,
    tags: ["indie", "live", "food"],
    icon: "sparkle",
  },
  {
    id: "crew-thrift",
    name: "Thrift + ramen run",
    category: "retail",
    start: "Thu • 17:00",
    location: "Canal District",
    capacity: { filled: 4, total: 7 },
    description: "Curated racks, fit-pics on the go, broth finish to compare finds.",
    compatibility: 86,
    tags: ["fashion", "casual", "ramen"],
    icon: "bag",
  },
]

export const friendsTemplates: FriendsTemplate[] = [
  {
    id: "template-beach-coffee",
    label: "Beach + coffee",
    categories: ["beach", "cafe"],
    summary: "Sunrise swim, pour-over kiosk, seaside stretch.",
    duration: "half-day",
    tags: ["sunrise", "chill", "daylight"],
  },
  {
    id: "template-hike-brunch",
    label: "Hike + brunch",
    categories: ["outdoor", "restaurant"],
    summary: "Trail climb into a recovery table with smoothies & shared plates.",
    duration: "half-day",
    tags: ["active", "recovery"],
  },
  {
    id: "template-cafe-crawl",
    label: "Cafe crawl",
    categories: ["cafe", "cowork"],
    summary: "Study session that turns into a print zine swap.",
    duration: "full-day",
    tags: ["creative", "steady"],
  },
  {
    id: "template-gallery-night",
    label: "Gallery + drinks",
    categories: ["event", "nightlife"],
    summary: "Late gallery preview with cocktail lounge finale.",
    duration: "evening",
    tags: ["culture", "night"],
  },
  {
    id: "template-gig-night",
    label: "Gig night",
    categories: ["event", "nightlife"],
    summary: "Soundcheck access, vibes matched, afterparty handled.",
    duration: "evening",
    tags: ["live", "high-energy"],
  },
  {
    id: "template-study-session",
    label: "Study session",
    categories: ["cowork", "cafe"],
    summary: "Quiet corners, productivity sprints, late-night bites.",
    duration: "late",
    tags: ["focus", "late-night"],
  },
]

export const uniTeasers = [
  {
    id: "societies",
    title: "Societies & events",
    description: "See what every club is running this week, filtered by your campus.",
  },
  {
    id: "study-buddies",
    title: "Study buddy finder",
    description: "Match by major, time zone, and grind window.",
  },
  {
    id: "campus-deals",
    title: "Campus deals",
    description: "Cafés, copy shops, and thrift spots near campus with student perks.",
  },
]

export const explorePlaces: ExplorePlace[] = [
  // Nightlife
  {
    id: "nightlife-velvet-spectrum",
    name: "Velvet Spectrum Rooftop",
    category: "nightlife",
    description: "Sunset aperitifs, vinyl selectors, and thermal lantern lounges overlooking the bay.",
    neighborhood: "Harbor Rise",
    distanceKm: 2.3,
    budget: "$60-$100",
    timeOfDay: "evening",
    duration: "half-day",
    tags: ["rooftop", "vinyl", "sunset"],
    openNow: true,
    slot: "Tonight • 19:00",
    image: "/placeholder.jpg",
    rating: 4.86,
    reviews: 312,
    isCrewFriendly: true,
  },
  {
    id: "nightlife-neon-harbor",
    name: "Neon Harbor Warehouse",
    category: "nightlife",
    description: "Multi-room club with motion-reactive lighting and live visuals synced to bands.",
    neighborhood: "Docklands",
    distanceKm: 3.8,
    budget: "$60-$100",
    timeOfDay: "late",
    duration: "half-day",
    tags: ["warehouse", "visuals", "afterhours"],
    openNow: false,
    slot: "Fri • 23:30",
    image: "/placeholder.jpg",
    rating: 4.92,
    reviews: 451,
    isCrewFriendly: true,
  },
  {
    id: "nightlife-shadowline",
    name: "Shadowline Listening Bar",
    category: "nightlife",
    description: "Analog hi-fi cocktails with curated ambient sets and velvet alcoves.",
    neighborhood: "Fifth Ward",
    distanceKm: 1.2,
    budget: "$30-$60",
    timeOfDay: "evening",
    duration: "short",
    tags: ["hi-fi", "cocktails", "seated"],
    openNow: true,
    image: "/placeholder.jpg",
    rating: 4.74,
    reviews: 188,
    isCrewFriendly: false,
  },
  {
    id: "nightlife-apollo-orbit",
    name: "Apollo Orbit Club",
    category: "nightlife",
    description: "360° stage, aerial performers, and crew-specific lighting cues.",
    neighborhood: "Orbital Plaza",
    distanceKm: 4.9,
    budget: "$100+",
    timeOfDay: "late",
    duration: "half-day",
    tags: ["360 stage", "performers", "crew lighting"],
    openNow: false,
    slot: "Sat • 00:30",
    image: "/placeholder.jpg",
    rating: 4.98,
    reviews: 529,
    isCrewFriendly: true,
  },
  {
    id: "nightlife-horizon-soiree",
    name: "Horizon Soirée Lounge",
    category: "nightlife",
    description: "Champagne flights, live strings, and scenic terrace fire pits.",
    neighborhood: "Sky Promenade",
    distanceKm: 2.7,
    budget: "$100+",
    timeOfDay: "evening",
    duration: "short",
    tags: ["strings", "champagne", "terrace"],
    openNow: true,
    image: "/placeholder.jpg",
    rating: 4.81,
    reviews: 267,
    isCrewFriendly: true,
  },
  {
    id: "nightlife-pulse-district",
    name: "Pulse District Block Party",
    category: "nightlife",
    description: "Outdoor DJ rotation with sponsor activations, pop-up dining, and safe rides built-in.",
    neighborhood: "Pulse District",
    distanceKm: 3.1,
    budget: "<$30",
    timeOfDay: "evening",
    duration: "half-day",
    tags: ["open-air", "food", "rides"],
    openNow: false,
    slot: "Sun • 18:00",
    image: "/placeholder.jpg",
    rating: 4.67,
    reviews: 198,
    isCrewFriendly: true,
  },
  // Restaurants
  {
    id: "restaurant-salt-ember",
    name: "Salt & Ember Chef's Table",
    category: "restaurant",
    description: "Ten-course coastal tasting with fire cooking, fermentation lab, and AI-paced pairings.",
    neighborhood: "Harbor",
    distanceKm: 2.2,
    budget: "$100+",
    timeOfDay: "evening",
    duration: "half-day",
    tags: ["tasting", "fire cooking", "pairings"],
    openNow: false,
    slot: "Thu • 20:00",
    image: "/placeholder.jpg",
    rating: 4.97,
    reviews: 186,
    isCrewFriendly: true,
  },
  {
    id: "restaurant-midnight-noodle",
    name: "Midnight Noodle Supper",
    category: "restaurant",
    description: "Late-night chef counter with seasonal broth flights and soy candlelit tables.",
    neighborhood: "Laneway East",
    distanceKm: 1.1,
    budget: "$30-$60",
    timeOfDay: "late",
    duration: "short",
    tags: ["late-night", "kotteri", "counter"],
    openNow: true,
    image: "/placeholder.jpg",
    rating: 4.83,
    reviews: 239,
    isCrewFriendly: true,
  },
  {
    id: "restaurant-greenhouse-ferment",
    name: "Greenhouse Ferment Kitchen",
    category: "restaurant",
    description: "Vegetable-forward dining with koji pantry, low-waste cocktails, and vinyl ambient.",
    neighborhood: "Verdant Row",
    distanceKm: 3.4,
    budget: "$60-$100",
    timeOfDay: "evening",
    duration: "half-day",
    tags: ["vegetable", "fermentation", "vinyl"],
    openNow: false,
    slot: "Fri • 19:30",
    image: "/placeholder.jpg",
    rating: 4.89,
    reviews: 164,
    isCrewFriendly: true,
  },
  {
    id: "restaurant-tidepool-oyster",
    name: "Tidepool Oyster Lab",
    category: "restaurant",
    description: "Raw bar residency with kelp martinis, tidepool projections, and DJed brunch.",
    neighborhood: "Seaboard",
    distanceKm: 2.8,
    budget: "$60-$100",
    timeOfDay: "afternoon",
    duration: "short",
    tags: ["oyster", "kelp", "brunch"],
    openNow: true,
    image: "/placeholder.jpg",
    rating: 4.76,
    reviews: 208,
    isCrewFriendly: true,
  },
  {
    id: "restaurant-celestial-salon",
    name: "Celestial Tasting Salon",
    category: "restaurant",
    description: "Projection dome dining with synchronized courses and aroma pairing.",
    neighborhood: "Halo Quarter",
    distanceKm: 4.1,
    budget: "$100+",
    timeOfDay: "evening",
    duration: "half-day",
    tags: ["immersive", "multi-sensory", "projection"],
    openNow: false,
    slot: "Sat • 21:00",
    image: "/placeholder.jpg",
    rating: 4.95,
    reviews: 129,
    isCrewFriendly: true,
  },
  {
    id: "restaurant-lowlight-tapas",
    name: "Lowlight Tapas Cellar",
    category: "restaurant",
    description: "Basement tapas with vermouth bar, flamenco sample loops, and communal feasts.",
    neighborhood: "Old Stone",
    distanceKm: 0.9,
    budget: "$30-$60",
    timeOfDay: "evening",
    duration: "short",
    tags: ["tapas", "vermouth", "communal"],
    openNow: true,
    image: "/placeholder.jpg",
    rating: 4.71,
    reviews: 302,
    isCrewFriendly: true,
  },
  // Cafés
  {
    id: "cafe-circuit-brew",
    name: "Circuit Brew Lab",
    category: "cafe",
    description: "Siphon flights, kinetic espresso bar, and robotics handoff for oat soft serve.",
    neighborhood: "Innovation Pier",
    distanceKm: 1.4,
    budget: "$30-$60",
    timeOfDay: "morning",
    duration: "short",
    tags: ["siphon", "robotic", "soft serve"],
    openNow: true,
    image: "/placeholder.jpg",
    rating: 4.88,
    reviews: 223,
    isCrewFriendly: false,
  },
  {
    id: "cafe-morning-assembly",
    name: "Morning Assembly Studio",
    category: "cafe",
    description: "Daylight gallery cafe with rotating roasters, playlists, and cowork pods.",
    neighborhood: "Atelier Row",
    distanceKm: 0.8,
    budget: "$30-$60",
    timeOfDay: "morning",
    duration: "half-day",
    tags: ["gallery", "cowork", "rotating"],
    openNow: true,
    image: "/placeholder.jpg",
    rating: 4.73,
    reviews: 178,
    isCrewFriendly: true,
  },
  {
    id: "cafe-solar-press",
    name: "Solar Press Patio",
    category: "cafe",
    description: "Sun-drenched patio with solar brewed cold coffee, herbaceous spritzers, and acoustic sets.",
    neighborhood: "Sun District",
    distanceKm: 2.5,
    budget: "<$30",
    timeOfDay: "afternoon",
    duration: "short",
    tags: ["cold brew", "patio", "acoustic"],
    openNow: true,
    image: "/placeholder.jpg",
    rating: 4.65,
    reviews: 201,
    isCrewFriendly: true,
  },
  {
    id: "cafe-archive-slow",
    name: "Archive Slow Bar",
    category: "cafe",
    description: "Pour-over masterclasses, DJ-led focus hours, and analog zine library.",
    neighborhood: "Stacks",
    distanceKm: 1.1,
    budget: "$30-$60",
    timeOfDay: "morning",
    duration: "short",
    tags: ["pour over", "focus", "zine"],
    openNow: false,
    slot: "Tomorrow • 09:00",
    image: "/placeholder.jpg",
    rating: 4.92,
    reviews: 154,
    isCrewFriendly: false,
  },
  {
    id: "cafe-nimbus-matcha",
    name: "Nimbus Matcha Loft",
    category: "cafe",
    description: "Cloud loft with ceremonial matcha flights, tatami pods, and breeze sensors.",
    neighborhood: "Cloudline",
    distanceKm: 3.3,
    budget: "$30-$60",
    timeOfDay: "afternoon",
    duration: "short",
    tags: ["matcha", "ceremony", "tatami"],
    openNow: false,
    slot: "Sat • 14:00",
    image: "/placeholder.jpg",
    rating: 4.84,
    reviews: 142,
    isCrewFriendly: false,
  },
  {
    id: "cafe-haven-analog",
    name: "Haven Analog Cafe",
    category: "cafe",
    description: "Analog listening booths, pastry residencies, and journaling sessions.",
    neighborhood: "North Arcade",
    distanceKm: 0.6,
    budget: "<$30",
    timeOfDay: "morning",
    duration: "short",
    tags: ["listening", "pastry", "journaling"],
    openNow: true,
    image: "/placeholder.jpg",
    rating: 4.69,
    reviews: 289,
    isCrewFriendly: true,
  },
  // Beaches
  {
    id: "beach-aurora-tide-pools",
    name: "Aurora Tide Pools",
    category: "beach",
    description: "Guided dawn dip with heated cloak delivery, tide intel, and drone photos.",
    neighborhood: "Aurora Bay",
    distanceKm: 5.2,
    budget: "$30-$60",
    timeOfDay: "morning",
    duration: "short",
    tags: ["guided", "drone", "heated"],
    openNow: true,
    slot: "Tomorrow • 05:50",
    image: "/placeholder.jpg",
    rating: 4.94,
    reviews: 198,
    isCrewFriendly: true,
  },
  {
    id: "beach-beacon-sunrise",
    name: "Beacon Sunrise Swim",
    category: "beach",
    description: "Crew-matched sunrise swim with safety kayaks, playlists, and shuttle return.",
    neighborhood: "Beacon Strand",
    distanceKm: 6.1,
    budget: "<$30",
    timeOfDay: "morning",
    duration: "half-day",
    tags: ["swim", "crew", "shuttle"],
    openNow: false,
    slot: "Wed • 06:10",
    image: "/placeholder.jpg",
    rating: 4.88,
    reviews: 317,
    isCrewFriendly: true,
  },
  {
    id: "beach-driftwood-stretch",
    name: "Driftwood Dawn Stretch",
    category: "beach",
    description: "Sunrise yoga with sand heaters, herbal steam, and curated breakfast pop-up.",
    neighborhood: "Driftwood",
    distanceKm: 4.4,
    budget: "$30-$60",
    timeOfDay: "morning",
    duration: "half-day",
    tags: ["yoga", "steam", "breakfast"],
    openNow: false,
    slot: "Thu • 06:30",
    image: "/placeholder.jpg",
    rating: 4.9,
    reviews: 204,
    isCrewFriendly: true,
  },
  {
    id: "beach-lowtide-bonfire",
    name: "Lowtide Bonfire Social",
    category: "beach",
    description: "Night bonfire with acoustic sets, s'mores kit, and ride tokens pre-loaded.",
    neighborhood: "South Jetty",
    distanceKm: 5.7,
    budget: "<$30",
    timeOfDay: "evening",
    duration: "half-day",
    tags: ["bonfire", "acoustic", "rides"],
    openNow: false,
    slot: "Fri • 20:00",
    image: "/placeholder.jpg",
    rating: 4.79,
    reviews: 156,
    isCrewFriendly: true,
  },
  {
    id: "beach-mirage-lagoon",
    name: "Mirage Lagoon Paddle",
    category: "beach",
    description: "Sunset SUP tour with LED boards, photo capture, and post-paddle hot cider.",
    neighborhood: "Lagoon",
    distanceKm: 7.8,
    budget: "$30-$60",
    timeOfDay: "evening",
    duration: "half-day",
    tags: ["SUP", "LED", "sunset"],
    openNow: false,
    slot: "Sat • 18:45",
    image: "/placeholder.jpg",
    rating: 4.82,
    reviews: 127,
    isCrewFriendly: true,
  },
  {
    id: "beach-sunspoke-lookout",
    name: "Sunspoke Cliff Lookout",
    category: "beach",
    description: "Sunrise lookout coffee service, drone shot prints, and guided meditation.",
    neighborhood: "Sunspoke Cliffs",
    distanceKm: 6.9,
    budget: "$30-$60",
    timeOfDay: "morning",
    duration: "short",
    tags: ["lookout", "coffee", "meditation"],
    openNow: false,
    slot: "Sun • 05:40",
    image: "/placeholder.jpg",
    rating: 4.91,
    reviews: 143,
    isCrewFriendly: true,
  },
  // Outdoors
  {
    id: "outdoor-skyline-traverse",
    name: "Skyline Ridge Traverse",
    category: "outdoor",
    description: "Sunrise ridge hike with pace coaching, shuttle return, and weather pivoting built-in.",
    neighborhood: "Skyline Reserve",
    distanceKm: 8.4,
    budget: "$30-$60",
    timeOfDay: "morning",
    duration: "half-day",
    tags: ["sunrise", "guide", "shuttle"],
    openNow: false,
    slot: "Sat • 05:20",
    image: "/placeholder.jpg",
    rating: 4.95,
    reviews: 276,
    isCrewFriendly: true,
  },
  {
    id: "outdoor-canyon-echo",
    name: "Canyon Echo Run",
    category: "outdoor",
    description: "Trail run crew with pacer bands, hydration drops, and live elevation coaching.",
    neighborhood: "Echo Canyon",
    distanceKm: 9.1,
    budget: "<$30",
    timeOfDay: "morning",
    duration: "short",
    tags: ["run", "pacer", "hydration"],
    openNow: true,
    image: "/placeholder.jpg",
    rating: 4.78,
    reviews: 143,
    isCrewFriendly: true,
  },
  {
    id: "outdoor-verdant-picnic",
    name: "Verdant Summit Picnic",
    category: "outdoor",
    description: "AI-packed picnic, hammock lounge, and ambient soundscapes overlooking the valley.",
    neighborhood: "Verdant Summit",
    distanceKm: 6.5,
    budget: "$30-$60",
    timeOfDay: "afternoon",
    duration: "half-day",
    tags: ["picnic", "hammock", "ambient"],
    openNow: false,
    slot: "Sun • 14:30",
    image: "/placeholder.jpg",
    rating: 4.83,
    reviews: 119,
    isCrewFriendly: true,
  },
  {
    id: "outdoor-cascade-suspension",
    name: "Cascade Suspension Trek",
    category: "outdoor",
    description: "Guided suspension bridge trek with waterfall snack stop and safety drone support.",
    neighborhood: "Cascade Range",
    distanceKm: 10.2,
    budget: "$60-$100",
    timeOfDay: "morning",
    duration: "half-day",
    tags: ["bridge", "waterfall", "safety"],
    openNow: false,
    slot: "Fri • 07:00",
    image: "/placeholder.jpg",
    rating: 4.87,
    reviews: 164,
    isCrewFriendly: true,
  },
  {
    id: "outdoor-grove-lantern",
    name: "Grove Lantern Walk",
    category: "outdoor",
    description: "Lantern-guided twilight walk through the grove with botanist narration and cocoa service.",
    neighborhood: "Willow Grove",
    distanceKm: 5.9,
    budget: "<$30",
    timeOfDay: "evening",
    duration: "short",
    tags: ["lantern", "botany", "cocoa"],
    openNow: false,
    slot: "Thu • 19:15",
    image: "/placeholder.jpg",
    rating: 4.8,
    reviews: 132,
    isCrewFriendly: true,
  },
  {
    id: "outdoor-starlight-camp",
    name: "Starlight Ridge Camp",
    category: "outdoor",
    description: "Overnight glamp with telescope concierge, firepit supper, and sunrise shuttle out.",
    neighborhood: "Starlight Ridge",
    distanceKm: 14.3,
    budget: "$100+",
    timeOfDay: "evening",
    duration: "full-day",
    tags: ["camp", "telescope", "glamp"],
    openNow: false,
    slot: "Weekend • 17:00",
    image: "/placeholder.jpg",
    rating: 4.93,
    reviews: 98,
    isCrewFriendly: true,
  },
  // Events
  {
    id: "event-after-hours-gallery",
    name: "After Hours Gallery Session",
    category: "event",
    description: "Curator-led preview, candlelit jazz set, and cocktail pairings in the courtyard.",
    neighborhood: "Riverside",
    distanceKm: 2.1,
    budget: "$60-$100",
    timeOfDay: "evening",
    duration: "half-day",
    tags: ["gallery", "jazz", "cocktail"],
    openNow: false,
    slot: "Fri • 19:00",
    image: "/placeholder.jpg",
    rating: 4.9,
    reviews: 212,
    isCrewFriendly: true,
  },
  {
    id: "event-indie-vinyl",
    name: "Indie Vinyl Market",
    category: "event",
    description: "Record fair with live pressing booth, coffee carts, and artist signings.",
    neighborhood: "Warehouse District",
    distanceKm: 1.7,
    budget: "<$30",
    timeOfDay: "afternoon",
    duration: "half-day",
    tags: ["records", "coffee", "signings"],
    openNow: true,
    image: "/placeholder.jpg",
    rating: 4.72,
    reviews: 188,
    isCrewFriendly: true,
  },
  {
    id: "event-steppers-rooftop",
    name: "Stepper's Rooftop Series",
    category: "event",
    description: "House & disco rooftop sessions with crew-colored wristbands and silent disco failover.",
    neighborhood: "Sky Market",
    distanceKm: 3.5,
    budget: "$30-$60",
    timeOfDay: "evening",
    duration: "half-day",
    tags: ["rooftop", "dance", "silent disco"],
    openNow: false,
    slot: "Sat • 18:00",
    image: "/placeholder.jpg",
    rating: 4.85,
    reviews: 264,
    isCrewFriendly: true,
  },
  {
    id: "event-quantum-light",
    name: "Quantum Light Installation",
    category: "event",
    description: "Immersive light maze with timed entries, AI-guided pathways, and ambient score.",
    neighborhood: "Nova Park",
    distanceKm: 2.9,
    budget: "$60-$100",
    timeOfDay: "evening",
    duration: "short",
    tags: ["immersive", "light", "timed"],
    openNow: false,
    slot: "Thu • 20:30",
    image: "/placeholder.jpg",
    rating: 4.91,
    reviews: 175,
    isCrewFriendly: true,
  },
  {
    id: "event-waypoint-forum",
    name: "Waypoint Creator Forum",
    category: "event",
    description: "Panels, breakout lounges, and sponsor labs with live scheduling via Bands.",
    neighborhood: "Convention Hub",
    distanceKm: 1.3,
    budget: "$60-$100",
    timeOfDay: "afternoon",
    duration: "full-day",
    tags: ["panels", "breakout", "sponsor"],
    openNow: false,
    slot: "Mon • 10:00",
    image: "/placeholder.jpg",
    rating: 4.76,
    reviews: 98,
    isCrewFriendly: true,
  },
  {
    id: "event-synthwave-roller",
    name: "Synthwave Roller Night",
    category: "event",
    description: "Retro rink takeover with live DJ, choreo leads, and safety marshals on call.",
    neighborhood: "Orbit Rink",
    distanceKm: 4.4,
    budget: "$30-$60",
    timeOfDay: "evening",
    duration: "half-day",
    tags: ["roller", "retro", "DJ"],
    openNow: false,
    slot: "Fri • 21:00",
    image: "/placeholder.jpg",
    rating: 4.82,
    reviews: 207,
    isCrewFriendly: true,
  },
  // Travel
  {
    id: "travel-coastline-weekender",
    name: "Coastline Weekender",
    category: "travel",
    description: "Train, boutique stay, sunrise hike, and tasting dinner locked by AI.",
    neighborhood: "Departing Central",
    distanceKm: 0,
    budget: "$100+",
    timeOfDay: "morning",
    duration: "full-day",
    tags: ["train", "stay", "dining"],
    openNow: true,
    slot: "Fri • 17:30",
    image: "/placeholder.jpg",
    rating: 4.9,
    reviews: 156,
    isCrewFriendly: true,
  },
  {
    id: "travel-mountain-steamline",
    name: "Mountain Steamline Escape",
    category: "travel",
    description: "Heritage train, alpine lodge, snowshoe loop, and hot spring recovery.",
    neighborhood: "Union Terminal",
    distanceKm: 0,
    budget: "$100+",
    timeOfDay: "morning",
    duration: "full-day",
    tags: ["train", "alpine", "hotspring"],
    openNow: false,
    slot: "Sat • 06:30",
    image: "/placeholder.jpg",
    rating: 4.96,
    reviews: 134,
    isCrewFriendly: true,
  },
  {
    id: "travel-desert-star",
    name: "Desert Star Getaway",
    category: "travel",
    description: "Waypoint charters desert glamp, astronomy concierge, and sunrise dune surf.",
    neighborhood: "Waypoint Terminal",
    distanceKm: 0,
    budget: "$100+",
    timeOfDay: "evening",
    duration: "full-day",
    tags: ["glamp", "astronomy", "dune"],
    openNow: false,
    slot: "Thu • 16:00",
    image: "/placeholder.jpg",
    rating: 4.87,
    reviews: 101,
    isCrewFriendly: true,
  },
  {
    id: "travel-harbor-boutique",
    name: "Harbor Boutique Stay",
    category: "travel",
    description: "Weekend harbor stay with sail charter, tasting menu, and city bikes keyed to the AI plan.",
    neighborhood: "Harborfront",
    distanceKm: 0,
    budget: "$100+",
    timeOfDay: "afternoon",
    duration: "full-day",
    tags: ["sail", "stay", "bikes"],
    openNow: true,
    image: "/placeholder.jpg",
    rating: 4.78,
    reviews: 118,
    isCrewFriendly: true,
  },
  {
    id: "travel-island-hop",
    name: "Island Hop Express",
    category: "travel",
    description: "Hydrofoil hop between islands with beach club access and AI-managed dining slots.",
    neighborhood: "Pier 7",
    distanceKm: 0,
    budget: "$100+",
    timeOfDay: "morning",
    duration: "full-day",
    tags: ["hydrofoil", "beach club", "dining"],
    openNow: false,
    slot: "Sun • 08:00",
    image: "/placeholder.jpg",
    rating: 4.83,
    reviews: 93,
    isCrewFriendly: true,
  },
  {
    id: "travel-wine-loop",
    name: "Countryside Wine Loop",
    category: "travel",
    description: "Driver + EV shuttle through vineyards with picnic hamper, live acoustic pairings, and ride home.",
    neighborhood: "Central Station",
    distanceKm: 0,
    budget: "$100+",
    timeOfDay: "afternoon",
    duration: "full-day",
    tags: ["vineyard", "acoustic", "shuttle"],
    openNow: false,
    slot: "Sat • 11:00",
    image: "/placeholder.jpg",
    rating: 4.9,
    reviews: 121,
    isCrewFriendly: true,
  },
  // Retail
  {
    id: "retail-foundry-vintage",
    name: "Foundry Vintage Crawl",
    category: "retail",
    description: "Guided vintage crawl with inventory intel, dressing room holds, and ramen finisher.",
    neighborhood: "Foundry Row",
    distanceKm: 2.6,
    budget: "<$30",
    timeOfDay: "afternoon",
    duration: "half-day",
    tags: ["vintage", "inventory", "ramen"],
    openNow: true,
    image: "/placeholder.jpg",
    rating: 4.77,
    reviews: 205,
    isCrewFriendly: true,
  },
  {
    id: "retail-flux-design",
    name: "Flux Design Market",
    category: "retail",
    description: "Designers in residence, AR product tags, and sponsor lounge espresso shots.",
    neighborhood: "Design Loop",
    distanceKm: 1.9,
    budget: "$30-$60",
    timeOfDay: "afternoon",
    duration: "half-day",
    tags: ["design", "AR", "espresso"],
    openNow: true,
    image: "/placeholder.jpg",
    rating: 4.82,
    reviews: 167,
    isCrewFriendly: true,
  },
  {
    id: "retail-arcade-sneaker",
    name: "Arcade Sneaker Drop",
    category: "retail",
    description: "Sneaker drop with queue intel, custom lace lab, and DJ-backed release.",
    neighborhood: "Arcade Quarter",
    distanceKm: 1.5,
    budget: "$30-$60",
    timeOfDay: "morning",
    duration: "short",
    tags: ["sneaker", "queue", "DJ"],
    openNow: false,
    slot: "Sat • 09:00",
    image: "/placeholder.jpg",
    rating: 4.7,
    reviews: 142,
    isCrewFriendly: true,
  },
  {
    id: "retail-midnight-makers",
    name: "Midnight Makers Row",
    category: "retail",
    description: "Night market with maker demos, bands pulse signage, and dessert alley.",
    neighborhood: "Maker's Row",
    distanceKm: 3.7,
    budget: "<$30",
    timeOfDay: "evening",
    duration: "half-day",
    tags: ["market", "demo", "dessert"],
    openNow: false,
    slot: "Fri • 19:30",
    image: "/placeholder.jpg",
    rating: 4.74,
    reviews: 184,
    isCrewFriendly: true,
  },
  {
    id: "retail-lumen-record",
    name: "Lumen Record Fair",
    category: "retail",
    description: "Underground record swap with hi-fi zones, listening pods, and coffee mods.",
    neighborhood: "Lumen Tunnel",
    distanceKm: 2.2,
    budget: "$30-$60",
    timeOfDay: "afternoon",
    duration: "half-day",
    tags: ["records", "hifi", "swap"],
    openNow: true,
    image: "/placeholder.jpg",
    rating: 4.69,
    reviews: 131,
    isCrewFriendly: true,
  },
  {
    id: "retail-threadline-textile",
    name: "Threadline Textile Lab",
    category: "retail",
    description: "Fabric lab with custom dye workshops, 3D weaving demos, and on-demand tailoring.",
    neighborhood: "Threadline",
    distanceKm: 2.8,
    budget: "$30-$60",
    timeOfDay: "afternoon",
    duration: "half-day",
    tags: ["textile", "workshop", "tailor"],
    openNow: false,
    slot: "Sun • 13:00",
    image: "/placeholder.jpg",
    rating: 4.81,
    reviews: 99,
    isCrewFriendly: true,
  },
  // Cowork / Study
  {
    id: "cowork-focus-district",
    name: "Focus District Loft",
    category: "cowork",
    description: "Quiet loft with AI noise monitoring, snack bar, and stand-up sprint schedule.",
    neighborhood: "Focus District",
    distanceKm: 0.7,
    budget: "$30-$60",
    timeOfDay: "afternoon",
    duration: "half-day",
    tags: ["focus", "snacks", "sprints"],
    openNow: true,
    image: "/placeholder.jpg",
    rating: 4.85,
    reviews: 142,
    isCrewFriendly: true,
  },
  {
    id: "cowork-archive-study",
    name: "Archive Study Club",
    category: "cowork",
    description: "Silent study hall with lockers, beverage service, and timed focus bells.",
    neighborhood: "Archive Wing",
    distanceKm: 0.9,
    budget: "$30-$60",
    timeOfDay: "afternoon",
    duration: "half-day",
    tags: ["silent", "lockers", "beverage"],
    openNow: true,
    image: "/placeholder.jpg",
    rating: 4.92,
    reviews: 178,
    isCrewFriendly: false,
  },
  {
    id: "cowork-noonlight-pods",
    name: "Noonlight Studio Pods",
    category: "cowork",
    description: "Studio pods for creators with lighting rigs, micro-stages, and live booking calendar.",
    neighborhood: "Noonlight",
    distanceKm: 1.5,
    budget: "$60-$100",
    timeOfDay: "afternoon",
    duration: "half-day",
    tags: ["studio", "creator", "lighting"],
    openNow: false,
    slot: "Wed • 12:00",
    image: "/placeholder.jpg",
    rating: 4.75,
    reviews: 124,
    isCrewFriendly: true,
  },
  {
    id: "cowork-grid-hub",
    name: "Grid Collaborative Hub",
    category: "cowork",
    description: "Open floor with project tables, pitch theatre, and AI note capture at each seat.",
    neighborhood: "Gridline",
    distanceKm: 1.2,
    budget: "$30-$60",
    timeOfDay: "afternoon",
    duration: "half-day",
    tags: ["collab", "pitch", "notes"],
    openNow: true,
    image: "/placeholder.jpg",
    rating: 4.7,
    reviews: 156,
    isCrewFriendly: true,
  },
  {
    id: "cowork-waypoint-commons",
    name: "Waypoint Uni Commons",
    category: "cowork",
    description: "Campus-verified commons with study pods, society board, and coffee stipend credit.",
    neighborhood: "Campus Core",
    distanceKm: 0.4,
    budget: "<$30",
    timeOfDay: "afternoon",
    duration: "half-day",
    tags: ["campus", "pods", "stipend"],
    openNow: true,
    image: "/placeholder.jpg",
    rating: 4.88,
    reviews: 203,
    isCrewFriendly: true,
  },
  {
    id: "cowork-orbit-hack-night",
    name: "Orbit Hack Night",
    category: "cowork",
    description: "Night hack session with mentors, energy drinks, and midnight noodle delivery.",
    neighborhood: "Orbit Labs",
    distanceKm: 1.9,
    budget: "$30-$60",
    timeOfDay: "late",
    duration: "half-day",
    tags: ["hack", "mentors", "noodles"],
    openNow: false,
    slot: "Thu • 22:00",
    image: "/placeholder.jpg",
    rating: 4.79,
    reviews: 147,
    isCrewFriendly: true,
  },
]

export const modeSpotlights: ModeSpotlight[] = [
  {
    mode: "Solo",
    headline: "Chase your own flow",
    description:
      "Waypoint strings sunrise dips, gallery drops, and night walks with buffers so you stay in rhythm without backtracking.",
    stats: [
      { label: "Avg build time", value: "3m", caption: "From prompt to full day" },
      { label: "Swap-ready stops", value: "12", caption: "Alternates per journey" },
      { label: "Safety pings", value: "3", caption: "Check-ins across the path" },
    ],
    playbook: [
      "Pick vibe + time window",
      "Tune pace from chill → packed",
      "Save, share, or convert to friends plan",
    ],
    cta: { label: "Launch Journey Builder", href: "/solo" },
  },
  {
    mode: "Discover",
    headline: "Meet your crew in minutes",
    description:
      "Match into 4–8 person squads for hikes, cafés, thrift crawls, or night sets — compatibility and safety layers locked.",
    stats: [
      { label: "Median match score", value: "92%", caption: "Vibe + schedule overlap" },
      { label: "Crew formats", value: "27", caption: "Across categories" },
      { label: "Queue skips", value: "18", caption: "Partner venues on tap" },
    ],
    playbook: [
      "Select categories + availability",
      "Preview crew energy + rules",
      "Tap to join, chat unlocks on arrival",
    ],
    cta: { label: "Find a crew", href: "/discover" },
  },
  {
    mode: "Friends",
    headline: "Orchestrate your whole squad",
    description:
      "Waypoint aligns calendars, budgets, polls, and reservations for city nights, campus crawls, or weekender escapes.",
    stats: [
      { label: "Calendar sync", value: "<30s", caption: "Per invite link" },
      { label: "Template library", value: "48", caption: "Category combos" },
      { label: "Plan satisfaction", value: "97%", caption: "Crew feedback" },
    ],
    playbook: [
      "Drop in the crew + vibe",
      "Toggle polls for categories + timing",
      "Waypoint books, nudges, and runs the night",
    ],
    cta: { label: "Launch the planner", href: "/friends" },
  },
]

export const citySignals: CitySignal[] = [
  {
    id: "signal-nightlife",
    category: "nightlife",
    status: "Peaking",
    change: 18,
    metric: "Late-night queue time",
    descriptor: "Rooftops up 18% vs last week",
  },
  {
    id: "signal-cafe",
    category: "cafe",
    status: "Trending",
    change: 12,
    metric: "Third-wave bookings",
    descriptor: "Study crawls filling midday slots",
  },
  {
    id: "signal-outdoor",
    category: "outdoor",
    status: "Watch",
    change: -6,
    metric: "Trail capacity",
    descriptor: "Weather pivot: coastal winds at sunrise",
  },
  {
    id: "signal-travel",
    category: "travel",
    status: "Trending",
    change: 9,
    metric: "Weekender demand",
    descriptor: "Train getaways booking out 48h sooner",
  },
]

export const cityEventHighlights: CityEventHighlight[] = [
  {
    id: "highlight-gallery",
    title: "After-hours gallery circuit",
    time: "Tonight • 21:30",
    category: "event",
    location: "Riverside Arts Wing",
    callout: "Waypoint holds your slot + afterparty",
  },
  {
    id: "highlight-club",
    title: "Warehouse sunrise set",
    time: "Sat • 04:00",
    category: "nightlife",
    location: "Docklands District",
    callout: "Bands auto-switch to dawn palette",
  },
  {
    id: "highlight-uni",
    title: "Campus makers night market",
    time: "Fri • 18:00",
    category: "retail",
    location: "Uni Courtyard",
    callout: "Verified with .edu wrist access",
  },
]

export const visualShowcase: VisualShowcase[] = [
  {
    id: "visual-sunrise-beach",
    title: "Sunrise Swim Club",
    subtitle: "Every Saturday, first light",
    category: "beach",
    image: "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=1400&q=80",
    location: "North Point Tidepool",
    tags: ["Sunrise", "Cold plunge", "Coffee truck"],
    description:
      "Waypoint unlocks heated towel service, tide intelligence, and post-swim coffee at the shoreline kiosk.",
    cta: { label: "Drop into Journey Builder", href: "/solo" },
  },
  {
    id: "visual-night-market",
    title: "Neon Night Market",
    subtitle: "Thursdays from 20:00",
    category: "retail",
    image: "https://images.unsplash.com/photo-1542317854-0d6d5beab9e1?auto=format&fit=crop&w=1400&q=80",
    location: "Canal District",
    tags: ["Street food", "Indie designers", "Live DJs"],
    description:
      "Bands glow to match each zone while Waypoint queues merch pickups, tasting flights, and afterparty access.",
    cta: { label: "Find a Discover crew", href: "/discover" },
  },
  {
    id: "visual-hike-brunch",
    title: "Skyline Ridge Walk",
    subtitle: "Weekender sunrise series",
    category: "outdoor",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80",
    location: "Skyline Reserve",
    tags: ["Guided", "Weather aware", "Brunch finish"],
    description:
      "Waypoint staggers start waves, pushes real-time weather calls, and preps recovery brunch when you arrive.",
    cta: { label: "Plan with friends", href: "/friends" },
  },
  {
    id: "visual-late-gallery",
    title: "Late Gallery + Jazz",
    subtitle: "Friday private viewing",
    category: "event",
    image: "https://images.unsplash.com/photo-1500530855697-40e5572ed87a?auto=format&fit=crop&w=1400&q=80",
    location: "Riverside Arts Wing",
    tags: ["Private tour", "Aperitif bar", "Basement jazz"],
    description:
      "Waypoint secures curator time, sets your cocktail pairing, and snaps a car to the after-hours lounge.",
    cta: { label: "View Explore feed", href: "/explore" },
  },
]
